### ISSUE TITLE
[BodyTracking] AttributeError: 'Tracker' object has no attribute '_handle'

### ISSUE THREAD

**Issue by yuukireina05** [ibaiGorordo/pyKinectAzure#52]
**My Desktop information**

- OS with Version: Ubuntu 20.04.3 LTS 64-bit
- CPU: Intel® Core™ i7-10700 CPU @ 2.90GHz × 16 (No independent GPU)
- SDK Version: 1.4.1
- Packages version: libk4a1.4, libk4abt1.1.0, k4a-tools1.4.1

I can run the `k4abt_simple_3d_viewer` by calling `k4abt_simple_3d_viewer CPU` in my terminal. Also no problem with the running of `k4aviewer` by calling it in the terminal. 
Python files except for body tracking parts can be run normally, such as `exampleColorImage.py` and `exampleDepthImage.py` and so on. 

**To reproduce:** 
1. Replace the `k4abt.so` in `utils/utils.py/def get_k4abt_module_path` with `libk4abt.so`
2. Replace the `k4abt_tracker_default_configuration.processing_mode` in `k4abt/_k4abtTypes.py` with `K4ABT_TRACKER_PROCESSING_MODE_CPU`
3. Run any python file for Body Tracking.

Error log:
```
[2022-02-11 11:08:38.189] [error] [t=3332] [K4ABT] ../src/TrackerHost/TrackerHost.cpp (185): Create(). /tmp/onnxruntime/onnxruntime/core/providers/cuda/cuda_call.cc:123 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /tmp/onnxruntime/onnxruntime/core/providers/cuda/cuda_call.cc:117 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=32745 ; hostname=nmed-OptiPlex-5080 ; expr=cudaSetDevice(device_id_); 

[2022-02-11 11:08:38.189] [error] [t=3332] [K4ABT] ../src/sdk/k4abt.cpp (38): tracker->Create(sensor_calibration, config) returned failure in k4abt_tracker_create()
Body tracker initialization failed!
  File "/home/nmed/OneDrive/CODE/Python/Azure-Kinect-python/examples/exampleBodyTracking.py", line 22, in <module>
    bodyTracker = pykinect.start_body_tracker()
  File "/home/nmed/OneDrive/CODE/Python/Azure-Kinect-python/examples/../pykinect_azure/pykinect.py", line 63, in start_body_tracker
    return Tracker(Device.calibration, model_type)
  File "/home/nmed/OneDrive/CODE/Python/Azure-Kinect-python/examples/../pykinect_azure/k4abt/tracker.py", line 11, in __init__
    self._handle = self.create(model_type)
  File "/home/nmed/OneDrive/CODE/Python/Azure-Kinect-python/examples/../pykinect_azure/k4abt/tracker.py", line 66, in create
    _k4abt.VERIFY(_k4abt.k4abt_tracker_create(self.calibration.handle(), tracker_config, tracker_handle), "Body tracker initialization failed!")
  File "/home/nmed/OneDrive/CODE/Python/Azure-Kinect-python/examples/../pykinect_azure/k4abt/_k4abt.py", line 157, in VERIFY
    traceback.print_stack()
Exception ignored in: <function Tracker.__del__ at 0x7fe997559d30>
Traceback (most recent call last):
  File "/home/nmed/OneDrive/CODE/Python/Azure-Kinect-python/examples/../pykinect_azure/k4abt/tracker.py", line 15, in __del__
    self.destroy()
  File "/home/nmed/OneDrive/CODE/Python/Azure-Kinect-python/examples/../pykinect_azure/k4abt/tracker.py", line 27, in destroy
    if self.is_valid():
  File "/home/nmed/OneDrive/CODE/Python/Azure-Kinect-python/examples/../pykinect_azure/k4abt/tracker.py", line 18, in is_valid
    return self._handle
AttributeError: 'Tracker' object has no attribute '_handle'
```
I would appreciate it if any suggestion you can give to me.

**Comment by yuukireina05** [comment]
I finally solved the problem by adjusting configuration in `pykinect.py`:
```
...
def init_k4abt(module_k4abt_path):

    _k4abt.setup_library(module_k4abt_path)

    try:
        ctypes.cdll.LoadLibrary("C:/Program Files/Azure Kinect Body Tracking SDK/tools/directml.dll")
    except Exception as e:
        k4abt_tracker_default_configuration.processing_mode = K4ABT_TRACKER_PROCESSING_MODE_CPU
        # k4abt_tracker_default_configuration.processing_mode  = K4ABT_TRACKER_PROCESSING_MODE_GPU_CUDA
...
```
Then it runs.
